name: Validate Portal JSONs

on:
  push:
    paths:
      - '_data/portals/*.json'
  pull_request:
    paths:
      - '_data/portals/*.json'
  workflow_dispatch:

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /_data/portals/PortalGroup.schema.json
          INPUT_JSONS:  /_data/portals/admin.json,/_data/portals/thirdparty.json,/_data/portals/us-govt.json,/_data/portals/user.json
      - name: Discord Webhook Notify
        if: ${{ failure() }}
        # uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          # Discord webhook URL. Should be stored in a secret and inserted as a context expression.
          webhookUrl: ${{ env.DiscordPsychoPingKey }}
          # Severity level - info, warn, or error
          #severity: # optional, default is error
          # Embed notification message. Use context expressions and environment variables to provide information. Default provides branch and user info.
          #description: # optional
          # Additional text after the notification message in case you want to retain the default message.
          #details: # optional
          # Footer for the embed. Defaults to severity.
          #footer: # optional
          # Text to be sent as normal text above the embed. Use context expressions and environment variables to provide information.
          #text: # optional
          # Username to display in discord.
          #username: # optional
          # Notification color in the form poundsign rrggbb (hex). Default determined by severity.
          #color: # optional
          # URL to png of discord avatar to use. Default is the GitHub monochrome mark cat logo.
          #avatarUrl: # optional
