name: Validate Portal JSONs

on:
  push:
    paths:
      - '_data/portals/*.json'
  pull_request:
    paths:
      - '_data/portals/*.json'
  workflow_dispatch:

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /_data/portals/PortalGroup.schema.json
          INPUT_JSONS:  /_data/portals/admin.json,/_data/portals/thirdparty.json,/_data/portals/us-govt.json,/_data/portals/user.json
      - name: Notify on Failure
        if: ${{ failure() }}
        uses: distributhor/workflow-webhook@2.0.2
        with:
          url: "https://discord.com/api/webhooks/907158414147321926/${{ env.DiscordPsychoPingKey }}"
          json: '{ "content": "<@264652399824601088>           \n\"repository\": \"${{github.event.repository.full_name}}\", \n\"number\": \"${{github.event.number}}\", \n\"created_at\": \"${{github.event.pull_request.created_at}}\", \n\"updated_at\": \"${{github.event.pull_request.updated_at}}\" \n,  \"embeds\": null"}'
